name: Docker Release

on:
  workflow_dispatch:

jobs:
  release:    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source  
      uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup multi-arch build tools
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7

    - name: Multi-arch Docker Build
      run: |
        make docker-push
